"""
Agrega columna SourceType MANUALMENTE a Google Sheets
Version simplificada que pide que lo hagas tu mismo
"""

print("\n" + "="*70)
print("MANUAL: AGREGAR COLUMNA 'SourceType' A GOOGLE SHEETS")
print("="*70 + "\n")

print("POR FAVOR SIGUE ESTOS PASOS:")
print()
print("1. Abre Google Sheets:")
print("   https://docs.google.com/spreadsheets/d/1EqWPiHdcYyMr5trEuiT_-lzPVEr0owOoDEtTsCIBxdg")
print()
print("2. En cada pestana (Jobs, LinkedIn, Indeed, Glassdoor):")
print("   - Encuentra la columna 'Source' (columna G)")
print("   - Haz click derecho en la columna H")
print("   - Selecciona 'Insertar 1 columna a la izquierda'")
print("   - Nombra la nueva columna: 'SourceType'")
print()
print("3. Valores que tendras en SourceType:")
print("   - 'Email Individual' = Email directo de recruiter")
print("   - 'Bulletin' = Boletin con multiples jobs (Glassdoor, LinkedIn, Indeed)")
print("   - 'Scraping - LinkedIn' = Jobs del scraper de LinkedIn")
print("   - 'Scraping - Indeed' = Jobs del scraper de Indeed")
print()
print("="*70)
print("BENEFICIO:")
print("="*70)
print("Con esta columna podras:")
print("- Ver cuantos jobs vienen de cada fuente")
print("- Identificar si los scrapers estan funcionando")
print("- Saber si un job vino de email viejo o scraping fresco")
print()
print("="*70)
print()
print("NOTA: Este paso es OPCIONAL pero muy util para debugging")
print("El sistema funcionara sin esta columna")
print()
